#include "baf_handle_service.h"
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>
#define WORKERS 16
static int failures;
#define CHECK(x,m) do{if(!(x)){fprintf(stderr,"FAIL: %s\n",m);failures++;}}while(0)
static int ready(const char*p){int i;for(i=0;i<100;i++){if(baf_handle_ping(p,100)==BAF_HANDLE_OK)return 1;usleep(10000);}return 0;}
static void concurrent(const char*p,const char*h){pid_t pid[WORKERS];int i,ok=0,rejected=0;for(i=0;i<WORKERS;i++){pid[i]=fork();if(pid[i]==0){unsigned char*a=NULL;size_t n=0;enum baf_handle_status s=baf_handle_resolve_and_consume(p,1000,h,"target-a",&a,&n);baf_handle_assertion_free(a,n);_exit(s==BAF_HANDLE_OK?0:(s==BAF_HANDLE_NOT_FOUND||s==BAF_HANDLE_CONSUMED)?10:20);}}for(i=0;i<WORKERS;i++){int s;if(waitpid(pid[i],&s,0)>0&&WIFEXITED(s)){if(WEXITSTATUS(s)==0)ok++;else if(WEXITSTATUS(s)==10)rejected++;}}CHECK(ok==1,"exactly one concurrent resolve succeeds");CHECK(rejected==WORKERS-1,"all other resolves fail closed");}
int main(void){char path[96],h[65],h2[65],h3[65];pid_t server;unsigned char *out=NULL;size_t n=0;const unsigned char assertion[]="header.payload.signature";snprintf(path,sizeof(path),"/tmp/xrdp-baf-handle-%ld.sock",(long)getpid());unlink(path);server=fork();if(server==0)_exit(baf_handle_service_run(path,64,120));CHECK(server>0&&ready(path),"service ready");CHECK(baf_handle_store(path,1000,assertion,sizeof(assertion)-1,time(NULL)+60,"target-a",h)==BAF_HANDLE_OK,"store assertion");CHECK(strlen(h)==64,"256-bit hex handle");CHECK(strstr(h,"header")==NULL,"handle does not contain assertion");CHECK(baf_handle_resolve_and_consume(path,1000,h,"wrong",&out,&n)==BAF_HANDLE_TARGET_MISMATCH,"target mismatch rejected");CHECK(baf_handle_resolve_and_consume(path,1000,h,"target-a",&out,&n)==BAF_HANDLE_OK&&n==sizeof(assertion)-1&&!memcmp(out,assertion,n),"resolve returns assertion");baf_handle_assertion_free(out,n);out=NULL;n=0;CHECK(baf_handle_resolve_and_consume(path,1000,h,"target-a",&out,&n)==BAF_HANDLE_NOT_FOUND,"second resolve rejected");CHECK(baf_handle_resolve_and_consume(path,1000,"bad","target-a",&out,&n)==BAF_HANDLE_BAD_REQUEST,"malformed handle rejected");memset(h2,'a',64);h2[64]=0;CHECK(baf_handle_resolve_and_consume(path,1000,h2,"target-a",&out,&n)==BAF_HANDLE_NOT_FOUND,"unknown handle rejected");CHECK(baf_handle_store(path,1000,assertion,sizeof(assertion)-1,time(NULL)+121,"target-a",h2)==BAF_HANDLE_BAD_REQUEST,"excessive lifetime rejected");CHECK(baf_handle_store(path,1000,assertion,sizeof(assertion)-1,time(NULL)-1,"target-a",h2)==BAF_HANDLE_BAD_REQUEST,"expired assertion rejected");{unsigned char *big=malloc(BAF_HANDLE_MAX_ASSERTION+1);CHECK(baf_handle_store(path,1000,big,BAF_HANDLE_MAX_ASSERTION+1,time(NULL)+60,"target-a",h2)==BAF_HANDLE_BAD_REQUEST,"oversize rejected");free(big);}CHECK(baf_handle_store(path,1000,assertion,sizeof(assertion)-1,time(NULL)+60,"target-a",h3)==BAF_HANDLE_OK,"store concurrent assertion");concurrent(path,h3);kill(server,SIGTERM);waitpid(server,NULL,0);unlink(path);CHECK(baf_handle_ping(path,100)==BAF_HANDLE_UNAVAILABLE,"unavailable service fails closed");return failures?1:0;}
